version: '3.3'

services:
  rails-coverage:
    build:
      context: .
      dockerfile: Dockerfile
    command: entrypoints/entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
  postgres-cov:
    image: postgres:12-alpine
    container_name: postgres-coverage
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  bundle_cache:
  postgres: